# Generated by Django 5.1.7 on 2025-10-10 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issuereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response to the request"),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='approval_level',
            field=models.CharField(choices=[('DEPT_HEAD', 'Department Head'), ('ADMIN', 'Admin')], default='ADMIN', help_text='Who needs to approve this request', max_length=10),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='original_requester',
            field=models.ForeignKey(blank=True, help_text='Original user who made the request (if forwarded by dept head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
